apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: trtk5xwsu-nodejs 
  janus-idp.io/tekton: trtk5xwsu-nodejs
  backstage.io/kubernetes-id: trtk5xwsu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: trtk5xwsu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml