apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: trtk5xwsu-nodejs-gitops
  description: This is GitOps manifest for trtk5xwsu-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=trtk5xwsu-nodejs
    backstage.io/kubernetes-id: trtk5xwsu-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: trtk5xwsu-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:trtk5xwsu-nodejs
