apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: trtk5xwsu-nodejs
  janus-idp.io/tekton: trtk5xwsu-nodejs
  backstage.io/kubernetes-id: trtk5xwsu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: trtk5xwsu-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
